---
title: "**Ingeniería Genética Xtrema**"
---

### Synbio
___
<details> 
<summary> *Gene X* </summary>


>FS001574.1 FS001574 library AE0 Solanum melongena cDNA clone AE003K21 3', mRNA sequence
CCACTTCTGGGAGAAAGGGAATATATTAAAGGAACACATTCCACAAAGAACAGATAATCCCAAGCAGAGT
TGGAATTCATCTATTGACCTTATACTTGGGACCTGTTGGCTAAGCACCACAGGATAGTAAAGAACCGGGG
AAGCAAGAGCGCTAAACAAGGTTCAACGTTATTATACATTCACAACAGAACAAAACAAGAGACACATATA
CCAGTCACTAAAGACTCATCCCGGGAATGTGAAGAGGTCGGCAATCCAGTTGAACACCTAACAAAACTAT
AGCCCTTAAATCACATCAAACATCCACACATTAGTGGTCCGAGAGAACACTTTATTCTAAACTGTTTTAT
CTAACAACAGAGAACAGGATCATATCAGCAGCACCAGCACACTTCGCCACCACCCAGTGAACTGCCACGT
TACTGAACTGATGCCATGTGAATAATCAAGTCCACCACTCGCGTGCTGTAACCCCATTCGTTGTCGTACC
ATGCAACAACCTTGACAAATTTCTTGCTCAATGCAATTCCAGCCTTGGCATCAAATATGCTTGATCTATT
GTCTCCCACAAAATCCGTGGATACCACATCATCTTCAGTGTAACCTAGAATTCCCTTCAATTTTCCT


[Source](https://www.ncbi.nlm.nih.gov/nuccore/FS001574.1/)


</details>


<details> 
<summary> *Analysis* </summary>


AUG


</details>


<br>


Synbio MP4 [Click aquí ¡¡¡](https://gennbio.github.io/I.G.X.5.mp4)


<br>


Demo (I.G.X.) MP4 [Click aquí ¡¡¡](https://gennbio.github.io/D1NN.mp4)
